"""Regression tests: every legacy Masry program must produce golden output.

The golden files in ``expected/`` were generated by running the original
``legacy/masry.py`` over the programs in ``programs/``.  A second test
re-runs the legacy interpreter itself and compares it against the new
AlArabiya pipeline, so drift is caught even if someone edits the goldens.
"""

from __future__ import annotations

import subprocess
import sys
from pathlib import Path

import pytest

from al_arabiya.compiler.frontend import compile_source
from al_arabiya.runtime.interpreter.interpreter import Interpreter

HERE = Path(__file__).parent
PROGRAMS = HERE / "programs"
EXPECTED = HERE / "expected"
LEGACY = HERE.parent.parent / "legacy" / "masry.py"

PROGRAM_FILES = sorted(
    path for path in PROGRAMS.iterdir() if path.suffix in {".arb", ".masr"}
)
LEGACY_SCRIPT = HERE.parent.parent / "legacy" / "masry.py"


def run_new(path: Path) -> list[str]:
    source = path.read_text(encoding="utf-8")
    result = compile_source(source, path.name)
    assert result.program is not None, [
        (d.code, d.message, d.location) for d in result.diagnostics
    ]
    lines: list[str] = []
    Interpreter(write=lines.append).run(result.program)
    return lines


def golden_lines(path: Path) -> list[str]:
    golden = EXPECTED / f"{path.name}.txt"
    assert golden.exists(), f"missing golden for {path.name}"
    return golden.read_text(encoding="utf-8").splitlines()


@pytest.mark.parametrize("program", PROGRAM_FILES, ids=lambda p: p.name)
def test_golden_output(program: Path):
    assert run_new(program) == golden_lines(program)


@pytest.mark.parametrize("program", PROGRAM_FILES, ids=lambda p: p.name)
def test_matches_legacy_interpreter(program: Path):
    if not LEGACY_SCRIPT.exists():
        pytest.skip("legacy/masry.py not available")
    completed = subprocess.run(
        [sys.executable, "-X", "utf8", str(LEGACY_SCRIPT), str(program)],
        capture_output=True,
        encoding="utf-8",
        check=False,
    )
    assert completed.returncode == 0, completed.stderr
    legacy_lines = completed.stdout.splitlines()
    assert run_new(program) == legacy_lines


def test_regression_set_is_not_empty():
    assert len(PROGRAM_FILES) >= 6


def test_original_program_is_included():
    names = {path.name for path in PROGRAM_FILES}
    assert "original.masr" in names
    assert "original.arb" in names
